//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class student {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal student() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.student", typeof(student).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افحص الحل.
        /// </summary>
        public static string checkSolution {
            get {
                return ResourceManager.GetString("checkSolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاجابة.
        /// </summary>
        public static string correctAnswer {
            get {
                return ResourceManager.GetString("correctAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خلل: لا يوجد مادة.
        /// </summary>
        public static string error_MaterialNotFound {
            get {
                return ResourceManager.GetString("error_MaterialNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نهاية الوظيفة.
        /// </summary>
        public static string homeWorkEnd {
            get {
                return ResourceManager.GetString("homeWorkEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انتهى موعد الوظيفة.
        /// </summary>
        public static string homeworkFinished {
            get {
                return ResourceManager.GetString("homeworkFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان الوظيفة.
        /// </summary>
        public static string homeworkName {
            get {
                return ResourceManager.GetString("homeworkName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مراجعة الوظيفة.
        /// </summary>
        public static string homeworkReview {
            get {
                return ResourceManager.GetString("homeworkReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بداية الوظيفة.
        /// </summary>
        public static string homeworkStart {
            get {
                return ResourceManager.GetString("homeworkStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وظيفة.
        /// </summary>
        public static string homeworkTitleIsNull {
            get {
                return ResourceManager.GetString("homeworkTitleIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل اجابتك.
        /// </summary>
        public static string insertYourAnswer {
            get {
                return ResourceManager.GetString("insertYourAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذه النظرية تمكنك من الحل بشكل افضل.
        /// </summary>
        public static string materialMessage {
            get {
                return ResourceManager.GetString("materialMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مادة للمراجعة.
        /// </summary>
        public static string materialReview {
            get {
                return ResourceManager.GetString("materialReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التالي.
        /// </summary>
        public static string nextQuestion {
            get {
                return ResourceManager.GetString("nextQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحل.
        /// </summary>
        public static string solution {
            get {
                return ResourceManager.GetString("solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حل.
        /// </summary>
        public static string solveMessage {
            get {
                return ResourceManager.GetString("solveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ابدأ.
        /// </summary>
        public static string start {
            get {
                return ResourceManager.GetString("start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موعد البدء.
        /// </summary>
        public static string startDate {
            get {
                return ResourceManager.GetString("startDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موضوع.
        /// </summary>
        public static string subject {
            get {
                return ResourceManager.GetString("subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موعد التسليم.
        /// </summary>
        public static string submissionDate {
            get {
                return ResourceManager.GetString("submissionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السؤال هو.
        /// </summary>
        public static string theQuestionIs {
            get {
                return ResourceManager.GetString("theQuestionIs", resourceCulture);
            }
        }
    }
}
